"""empty message

Revision ID: 10c8a49cf5f
Revises: 1dd79d617182
Create Date: 2014-08-09 21:52:13.486049

"""

# revision identifiers, used by Alembic.
revision = '10c8a49cf5f'
down_revision = '1dd79d617182'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
