"""empty message

Revision ID: 16040d273353
Revises: 4ba385573e79
Create Date: 2014-09-14 01:25:56.632085

"""

# revision identifiers, used by Alembic.
revision = '16040d273353'
down_revision = '4ba385573e79'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
