"""empty message

Revision ID: 18d4781e3548
Revises: 26f8eae1dba
Create Date: 2014-08-13 15:04:44.791270

"""

# revision identifiers, used by Alembic.
revision = '18d4781e3548'
down_revision = '26f8eae1dba'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
