"""empty message

Revision ID: 1cc0bf39e7fc
Revises: 18d4781e3548
Create Date: 2014-08-28 17:32:18.470914

"""

# revision identifiers, used by Alembic.
revision = '1cc0bf39e7fc'
down_revision = '18d4781e3548'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('photo_id', sa.Integer(), nullable=True),
    sa.Column('msg_id', sa.Integer(), nullable=True),
    sa.Column('tag', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['msg_id'], ['message.msg_id'], ),
    sa.ForeignKeyConstraint(['photo_id'], ['left.file_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tag')
    ### end Alembic commands ###
