"""empty message

Revision ID: 1dd79d617182
Revises: 4aa18d81112b
Create Date: 2014-08-09 21:49:28.497150

"""

# revision identifiers, used by Alembic.
revision = '1dd79d617182'
down_revision = '4aa18d81112b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
