"""empty message

Revision ID: 1eaee12eb99a
Revises: 45ee470043c3
Create Date: 2014-09-06 01:51:47.742798

"""

# revision identifiers, used by Alembic.
revision = '1eaee12eb99a'
down_revision = '45ee470043c3'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('left', sa.Column('acceess', sa.Enum(u'file_exchange', u'public', u'private', u'reserve'), nullable=True))
    op.drop_column('left', 'filetype')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('left', sa.Column('filetype', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True))
    op.drop_column('left', 'acceess')
    ### end Alembic commands ###
