"""empty message

Revision ID: 1f49471f9f0e
Revises: 270f116c27bf
Create Date: 2014-08-28 18:56:14.371917

"""

# revision identifiers, used by Alembic.
revision = '1f49471f9f0e'
down_revision = '270f116c27bf'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity')
    )
    op.create_table('tags',
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.Column('left_id', sa.Integer(), nullable=True),
    sa.Column('message_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['left_id'], ['left.file_id'], ),
    sa.ForeignKeyConstraint(['message_id'], ['message.msg_id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], )
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tags')
    op.drop_table('tag')
    ### end Alembic commands ###
