"""empty message

Revision ID: 20e9a09a2805
Revises: 227521d7c190
Create Date: 2014-08-28 22:10:45.608756

"""

# revision identifiers, used by Alembic.
revision = '20e9a09a2805'
down_revision = '227521d7c190'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'entity', 'tag')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(u'entity', 'tag', ['entity'])
    ### end Alembic commands ###
