"""empty message

Revision ID: 227521d7c190
Revises: 1f49471f9f0e
Create Date: 2014-08-28 22:09:12.069788

"""

# revision identifiers, used by Alembic.
revision = '227521d7c190'
down_revision = '1f49471f9f0e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'entity', 'tag')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(u'entity', 'tag', ['entity'])
    ### end Alembic commands ###
