"""empty message

Revision ID: 24cf3faa73e5
Revises: 1cc0bf39e7fc
Create Date: 2014-08-28 18:28:50.303376

"""

# revision identifiers, used by Alembic.
revision = '24cf3faa73e5'
down_revision = '1cc0bf39e7fc'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.Column('left_id', sa.Integer(), nullable=True),
    sa.Column('message_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['left_id'], ['left.file_id'], ),
    sa.ForeignKeyConstraint(['message_id'], ['message.msg_id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], )
    )
    op.drop_column(u'tag', 'msg_id')
    op.drop_column(u'tag', 'photo_id')
    op.create_unique_constraint(None, 'tag', ['tag'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tag')
    op.add_column(u'tag', sa.Column('photo_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column(u'tag', sa.Column('msg_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_table('tags')
    ### end Alembic commands ###
