"""empty message

Revision ID: 26f8eae1dba
Revises: 42e5bfba80c0
Create Date: 2014-08-12 15:00:20.516832

"""

# revision identifiers, used by Alembic.
revision = '26f8eae1dba'
down_revision = '42e5bfba80c0'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exif', sa.Column('exposure_divident', sa.SmallInteger(), nullable=True))
    op.add_column('exif', sa.Column('exposure_divisor', sa.SmallInteger(), nullable=True))
    op.drop_column('exif', 'exposure')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exif', sa.Column('exposure', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('exif', 'exposure_divisor')
    op.drop_column('exif', 'exposure_divident')
    ### end Alembic commands ###
