"""empty message

Revision ID: 270f116c27bf
Revises: 3e281c215348
Create Date: 2014-08-28 18:54:57.663509

"""

# revision identifiers, used by Alembic.
revision = '270f116c27bf'
down_revision = '3e281c215348'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
