"""empty message

Revision ID: 287e1ec73ac6
Revises: 7578e3cae30
Create Date: 2014-11-07 17:51:08.499699

"""

# revision identifiers, used by Alembic.
revision = '287e1ec73ac6'
down_revision = '7578e3cae30'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group', sa.Column('date_create', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('group', 'date_create')
    ### end Alembic commands ###
