"""empty message

Revision ID: 2c0b54a3cd3f
Revises: 24cf3faa73e5
Create Date: 2014-08-28 18:45:35.208676

"""

# revision identifiers, used by Alembic.
revision = '2c0b54a3cd3f'
down_revision = '24cf3faa73e5'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tag', sa.Column('entity', sa.String(length=32), nullable=True))
    op.drop_column('tag', 'msg_id')
    op.drop_column('tag', 'photo_id')
    op.drop_column('tag', 'tag')
    op.create_unique_constraint(None, 'tag', ['entity'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tag')
    op.add_column('tag', sa.Column('tag', mysql.VARCHAR(collation=u'utf8_unicode_ci', length=32), nullable=True))
    op.add_column('tag', sa.Column('photo_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('tag', sa.Column('msg_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('tag', 'entity')
    ### end Alembic commands ###
