"""empty message

Revision ID: 2c746d735f27
Revises: 16040d273353
Create Date: 2014-09-14 01:27:15.958692

"""

# revision identifiers, used by Alembic.
revision = '2c746d735f27'
down_revision = '16040d273353'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tag', sa.Column('entity', sa.String(length=32), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tag', 'entity')
    ### end Alembic commands ###
