"""empty message

Revision ID: 2cadd64b0507
Revises: 696c733d884
Create Date: 2014-08-12 12:29:00.761412

"""

# revision identifiers, used by Alembic.
revision = '2cadd64b0507'
down_revision = '696c733d884'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exif',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('photo_id', sa.Integer(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('iso', sa.Integer(), nullable=True),
    sa.Column('model', sa.String(length=255), nullable=True),
    sa.Column('lens_model', sa.String(length=255), nullable=True),
    sa.Column('date', sa.String(length=32), nullable=True),
    sa.Column('exposure', sa.Integer(), nullable=True),
    sa.Column('fnumber', sa.SmallInteger(), nullable=True),
    sa.ForeignKeyConstraint(['photo_id'], ['left.file_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exif')
    ### end Alembic commands ###
