"""empty message

Revision ID: 2d61590d64a8
Revises: 40b8b3681b8b
Create Date: 2014-08-31 17:09:49.698411

"""

# revision identifiers, used by Alembic.
revision = '2d61590d64a8'
down_revision = '40b8b3681b8b'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exif', 'fnumber')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exif', sa.Column('fnumber', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True))
    ### end Alembic commands ###
