"""empty message

Revision ID: 2d631d777238
Revises: 5a41a1360561
Create Date: 2014-09-03 21:59:57.109343

"""

# revision identifiers, used by Alembic.
revision = '2d631d777238'
down_revision = '5a41a1360561'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('left', sa.Column('filetype', sa.SmallInteger(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('left', 'filetype')
    ### end Alembic commands ###
