"""empty message

Revision ID: 3486e98c1402
Revises: 3faa99811727
Create Date: 2014-08-28 22:31:02.710055

"""

# revision identifiers, used by Alembic.
revision = '3486e98c1402'
down_revision = '3faa99811727'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'tag', ['entity'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tag')
    ### end Alembic commands ###
