"""empty message

Revision ID: 3530d84dbf6d
Revises: 20e9a09a2805
Create Date: 2014-08-28 22:11:16.404289

"""

# revision identifiers, used by Alembic.
revision = '3530d84dbf6d'
down_revision = '20e9a09a2805'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tag', 'entity')
    op.drop_constraint(u'entity', 'tag')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(u'entity', 'tag', ['entity'])
    op.add_column('tag', sa.Column('entity', mysql.VARCHAR(collation=u'utf8_unicode_ci', length=32), nullable=True))
    ### end Alembic commands ###
