"""empty message

Revision ID: 3d404fa73580
Revises: 524530dab0dd
Create Date: 2014-10-30 17:25:27.918078

"""

# revision identifiers, used by Alembic.
revision = '3d404fa73580'
down_revision = '524530dab0dd'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
