"""empty message

Revision ID: 3e281c215348
Revises: 2c0b54a3cd3f
Create Date: 2014-08-28 18:49:17.603719

"""

# revision identifiers, used by Alembic.
revision = '3e281c215348'
down_revision = '2c0b54a3cd3f'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tag')
    op.drop_table('tags')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('tag_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('left_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('message_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['left_id'], [u'left.file_id'], name=u'tags_ibfk_1'),
    sa.ForeignKeyConstraint(['message_id'], [u'message.msg_id'], name=u'tags_ibfk_2'),
    sa.ForeignKeyConstraint(['tag_id'], [u'tag.id'], name=u'tags_ibfk_3'),
    mysql_collate=u'utf8_unicode_ci',
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.create_table('tag',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('photo_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('msg_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('tag', mysql.VARCHAR(collation=u'utf8_unicode_ci', length=32), nullable=True),
    sa.Column('entity', mysql.VARCHAR(collation=u'utf8_unicode_ci', length=32), nullable=True),
    sa.ForeignKeyConstraint(['msg_id'], [u'message.msg_id'], name=u'tag_ibfk_1'),
    sa.ForeignKeyConstraint(['photo_id'], [u'left.file_id'], name=u'tag_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate=u'utf8_unicode_ci',
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    ### end Alembic commands ###
