"""empty message

Revision ID: 3faa99811727
Revises: 5259d133d343
Create Date: 2014-08-28 22:12:28.760347

"""

# revision identifiers, used by Alembic.
revision = '3faa99811727'
down_revision = '5259d133d343'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tag', sa.Column('entity', sa.String(length=32), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tag', 'entity')
    ### end Alembic commands ###
