"""empty message

Revision ID: 40b8b3681b8b
Revises: 3486e98c1402
Create Date: 2014-08-31 17:08:11.822093

"""

# revision identifiers, used by Alembic.
revision = '40b8b3681b8b'
down_revision = '3486e98c1402'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
