"""empty message

Revision ID: 42e5bfba80c0
Revises: 2cadd64b0507
Create Date: 2014-08-12 13:07:22.576319

"""

# revision identifiers, used by Alembic.
revision = '42e5bfba80c0'
down_revision = '2cadd64b0507'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
