"""empty message

Revision ID: 45ee470043c3
Revises: 505e24f20892
Create Date: 2014-09-05 21:22:27.621378

"""

# revision identifiers, used by Alembic.
revision = '45ee470043c3'
down_revision = '505e24f20892'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('left', sa.Column('mimetype', sa.String(length=128), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('left', 'mimetype')
    ### end Alembic commands ###
