"""empty message

Revision ID: 461a118bdb89
Revises: 4d0168736583
Create Date: 2014-11-02 20:17:14.773605

"""

# revision identifiers, used by Alembic.
revision = '461a118bdb89'
down_revision = '4d0168736583'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
