"""empty message

Revision ID: 47db0af314b2
Revises: 487390998eca
Create Date: 2014-09-12 21:12:38.032873

"""

# revision identifiers, used by Alembic.
revision = '47db0af314b2'
down_revision = '487390998eca'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_exif_date'), 'exif', ['date'], unique=False)
    op.create_index(op.f('ix_exif_lens_model'), 'exif', ['lens_model'], unique=False)
    op.create_index(op.f('ix_exif_model'), 'exif', ['model'], unique=False)
    op.create_index(op.f('ix_exif_photo_id'), 'exif', ['photo_id'], unique=False)
    op.create_index(op.f('ix_left_msg_id'), 'left', ['msg_id'], unique=False)
    op.alter_column('message', 'del_from_author',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('message', 'del_from_dest',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('message', 'is_read',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.create_index(op.f('ix_message_is_read'), 'message', ['is_read'], unique=False)
    op.create_index(op.f('ix_message_msg_author'), 'message', ['msg_author'], unique=False)
    op.create_index(op.f('ix_message_msg_dest'), 'message', ['msg_dest'], unique=False)
    op.create_index(op.f('ix_message_msg_type'), 'message', ['msg_type'], unique=False)
    op.create_index(op.f('ix_message_timestamp'), 'message', ['timestamp'], unique=False)
    op.create_index(op.f('ix_right_author'), 'right', ['author'], unique=False)
    op.create_index(op.f('ix_tag_entity'), 'tag', ['entity'], unique=True)
    op.drop_constraint(u'entity', 'tag')
    op.create_index(op.f('ix_user_realname'), 'user', ['realname'], unique=False)
    op.drop_index('ix_user_password', table_name='user')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_user_password', 'user', ['password'], unique=False)
    op.drop_index(op.f('ix_user_realname'), table_name='user')
    op.create_unique_constraint(u'entity', 'tag', ['entity'])
    op.drop_index(op.f('ix_tag_entity'), table_name='tag')
    op.drop_index(op.f('ix_right_author'), table_name='right')
    op.drop_index(op.f('ix_message_timestamp'), table_name='message')
    op.drop_index(op.f('ix_message_msg_type'), table_name='message')
    op.drop_index(op.f('ix_message_msg_dest'), table_name='message')
    op.drop_index(op.f('ix_message_msg_author'), table_name='message')
    op.drop_index(op.f('ix_message_is_read'), table_name='message')
    op.alter_column('message', 'is_read',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('message', 'del_from_dest',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('message', 'del_from_author',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.drop_index(op.f('ix_left_msg_id'), table_name='left')
    op.drop_index(op.f('ix_exif_photo_id'), table_name='exif')
    op.drop_index(op.f('ix_exif_model'), table_name='exif')
    op.drop_index(op.f('ix_exif_lens_model'), table_name='exif')
    op.drop_index(op.f('ix_exif_date'), table_name='exif')
    ### end Alembic commands ###
