"""empty message

Revision ID: 48dd4abc2f44
Revises: 646c4b29aa7
Create Date: 2014-09-11 17:52:18.780228

"""

# revision identifiers, used by Alembic.
revision = '48dd4abc2f44'
down_revision = '646c4b29aa7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
