"""empty message

Revision ID: 4ba385573e79
Revises: 2b82dbdcfe12
Create Date: 2014-09-14 01:24:41.683897

"""

# revision identifiers, used by Alembic.
revision = '4ba385573e79'
down_revision = '2b82dbdcfe12'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('message', 'del_from_author',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('message', 'del_from_dest',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('message', 'is_read',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.drop_column('tag', 'entity')
    op.drop_constraint(u'entity', 'tag')
    op.drop_constraint(u'ix_tag_entity', 'tag')
    op.drop_index('ix_tag_entity', table_name='tag')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_tag_entity', 'tag', ['entity'], unique=True)
    op.create_unique_constraint(u'ix_tag_entity', 'tag', ['entity'])
    op.create_unique_constraint(u'entity', 'tag', ['entity'])
    op.add_column('tag', sa.Column('entity', mysql.VARCHAR(collation=u'utf8_unicode_ci', length=32), nullable=True))
    op.alter_column('message', 'is_read',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('message', 'del_from_dest',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('message', 'del_from_author',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    ### end Alembic commands ###
