"""empty message

Revision ID: 505e24f20892
Revises: 2d631d777238
Create Date: 2014-09-04 23:15:05.792847

"""

# revision identifiers, used by Alembic.
revision = '505e24f20892'
down_revision = '2d631d777238'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('left', sa.Column('msg_id', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('left', 'msg_id')
    ### end Alembic commands ###
