"""empty message

Revision ID: 524530dab0dd
Revises: bfe5f611ed9
Create Date: 2014-10-30 17:10:06.370909

"""

# revision identifiers, used by Alembic.
revision = '524530dab0dd'
down_revision = 'bfe5f611ed9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=2048), nullable=True),
    sa.Column('pic', sa.String(length=255), nullable=True),
    sa.Column('owner', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_group_owner'), 'group', ['owner'], unique=False)
    op.create_table('group_admin',
    sa.Column('participant_id', sa.Integer(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
    sa.ForeignKeyConstraint(['participant_id'], ['user.id'], )
    )
    op.create_index(op.f('ix_group_admin_group_id'), 'group_admin', ['group_id'], unique=False)
    op.create_index(op.f('ix_group_admin_participant_id'), 'group_admin', ['participant_id'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_group_admin_participant_id'), table_name='group_admin')
    op.drop_index(op.f('ix_group_admin_group_id'), table_name='group_admin')
    op.drop_table('group_admin')
    op.drop_index(op.f('ix_group_owner'), table_name='group')
    op.drop_table('group')
    ### end Alembic commands ###
