"""empty message

Revision ID: 5259d133d343
Revises: 3530d84dbf6d
Create Date: 2014-08-28 22:12:03.320496

"""

# revision identifiers, used by Alembic.
revision = '5259d133d343'
down_revision = '3530d84dbf6d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
