"""empty message

Revision ID: 54f87174c12e
Revises: 2d61590d64a8
Create Date: 2014-08-31 17:13:16.165708

"""

# revision identifiers, used by Alembic.
revision = '54f87174c12e'
down_revision = '2d61590d64a8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
