"""empty message

Revision ID: 5a41a1360561
Revises: 54f87174c12e
Create Date: 2014-08-31 17:29:42.507074

"""

# revision identifiers, used by Alembic.
revision = '5a41a1360561'
down_revision = '54f87174c12e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
