"""empty message

Revision ID: 646c4b29aa7
Revises: 6e48d129f44
Create Date: 2014-09-09 00:10:00.145670

"""

# revision identifiers, used by Alembic.
revision = '646c4b29aa7'
down_revision = '6e48d129f44'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exif', sa.Column('flash', sa.SmallInteger(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exif', 'flash')
    ### end Alembic commands ###
