"""empty message

Revision ID: 696c733d884
Revises: 3df8b107582a
Create Date: 2014-08-11 18:43:11.588882

"""

# revision identifiers, used by Alembic.
revision = '696c733d884'
down_revision = '3df8b107582a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('left', sa.Column('name', sa.String(length=255), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('left', 'name')
    ### end Alembic commands ###
