"""empty message

Revision ID: 6e48d129f44
Revises: 59b009e948f9
Create Date: 2014-09-09 00:00:00.464615

"""

# revision identifiers, used by Alembic.
revision = '6e48d129f44'
down_revision = '59b009e948f9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exif', sa.Column('focallength', sa.Float(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exif', 'focallength')
    ### end Alembic commands ###
