"""empty message

Revision ID: 7578e3cae30
Revises: 461a118bdb89
Create Date: 2014-11-04 20:27:38.814642

"""

# revision identifiers, used by Alembic.
revision = '7578e3cae30'
down_revision = '461a118bdb89'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tags', sa.Column('group_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_tags_group_id'), 'tags', ['group_id'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tags_group_id'), table_name='tags')
    op.drop_column('tags', 'group_id')
    ### end Alembic commands ###
