"""empty message

Revision ID: bfe5f611ed9
Revises: 2c746d735f27
Create Date: 2014-09-27 19:23:11.491769

"""

# revision identifiers, used by Alembic.
revision = 'bfe5f611ed9'
down_revision = '2c746d735f27'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_online_time', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_online_time')
    ### end Alembic commands ###
