"""empty message

Revision ID: f461bfac963
Revises: 3992f3c36823
Create Date: 2014-08-09 22:14:11.842479

"""

# revision identifiers, used by Alembic.
revision = 'f461bfac963'
down_revision = '3992f3c36823'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
